# Generated by Django 6.0.2 on 2026-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="latitude",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="Из EXIF GPS или ручной ввод",
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="longitude",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="Из EXIF GPS или ручной ввод",
                null=True,
                verbose_name="Долгота",
            ),
        ),
    ]
