# Generated by Django 5.2 on 2026-02-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_photo_latitude_photo_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yaw",
                    models.FloatField(
                        help_text="Горизонтальный угол стрелки в сцене (0-360°)",
                        verbose_name="Yaw (°)",
                    ),
                ),
                (
                    "pitch",
                    models.FloatField(
                        default=0,
                        help_text="Вертикальный угол стрелки в сцене",
                        verbose_name="Pitch (°)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "from_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_from",
                        to="photos.photo",
                        verbose_name="Из фото",
                    ),
                ),
                (
                    "to_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_to",
                        to="photos.photo",
                        verbose_name="В фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь фото",
                "verbose_name_plural": "Связи фото",
                "unique_together": {("from_photo", "to_photo")},
            },
        ),
    ]
