# Generated by Django 5.2 on 2026-02-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="GPS координата здания/объекта",
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="GPS координата здания/объекта",
                null=True,
                verbose_name="Долгота",
            ),
        ),
    ]
